### ISSUE TITLE
Can't see entire error

### ISSUE THREAD

**Issue by kylemcdougle** [rmotr-curriculum/advanced-python-programming#1]
When I run the code and get an error I can't read the entire line of code. It cuts off when my right side screen (where I input the code) starts. I can't scroll over to view it as well.

**Comment by santiagobasulto** [comment]
Thanks Kyle! I'll try to replicate and fix. If you have a screenshot please share it, it helps a lot.

**Comment by kylemcdougle** [comment]
Hey Santiago,

Sorry about that, I got it fixed. It was on my end. I use this app called
extension and it messed up my window.

Kyle McDougle
mcdougle.kyle@gmail.com
949.378.3547

On Mon, Jul 17, 2017 at 10:24 AM, Santiago Basulto <notifications@github.com

**Comment by santiagobasulto** [comment]
oh, thanks Kyle!
